# Justfile for Terraform to YAML conversion using yq

extract:
  #!/usr/bin/env bash
  set -euxo pipefail
  echo "Extracting Terraform state to YAML..."
  importedRepo=$(terraform show -json | jq -c '.values.root_module.child_modules[].resources[] | select(.type == "github_repository")')
  repoName=$(echo "$importedRepo" | jq -r '.values.name')
  repoConfig=$(echo "$importedRepo" | jq '
    {
      description: .values.description,
      visibility: .values.visibility,
      topics: .values.topics,
      has_issues: .values.has_issues,
      has_projects: .values.has_projects,
      has_wiki: .values.has_wiki,
      has_downloads: .values.has_downloads
    }')
  echo "$repoConfig" | jq -r '.' > $repoName.yml
  mv $repoName.yml ../../feature/github-repo-provisioning/repo_configs/

import-repo repoName:
  terraform import module.repository.github_repository.repository {{repoName}}

remove-imported-repo:
  terraform state rm module.repository.github_repository.repository