import-repo repoName:
  #!/usr/bin/env bash
  ./importer --import {{repoName}}
  IFS='/' read -r owner repo <<< {{repoName}}
  mv "$repo.yaml" "../../feature/github-repo-provisioning/repo_configs/generated/"

remove-imported-repo:
  terraform state rm module.repository.github_repository.repository
  terraform state rm 'module.repository.github_branch_default.default[0]'

test:
  go test ./...

build:
  go build -o importer cmd/importer/main.go