name: Import repo pipeline

on:
  workflow_dispatch:
    inputs:
      full_repo_name_with_org:
        description: 'The name of the repository to import with org name: format <org>/<repo>'
        required: true

jobs:
  import-repo:
    runs-on: ubuntu-latest
    name: Import repo
    environment: import
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Just
        uses: extractions/setup-just@v2
        with:
          just-version: '1.4.0'

      - name: Generate a token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Build binary
        working-directory: feature/github-repo-importer
        run: just build

      - name: Import repo
        working-directory: feature/github-repo-importer
        run: just import-repo ${{ github.event.inputs.full_repo_name_with_org }}
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - run: |
          git config --global user.name '${{ steps.generate-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - run: |
          git checkout -b import-repo-${{ github.event.inputs.full_repo_name_with_org }}
          git push --set-upstream origin import-repo-${{ github.event.inputs.full_repo_name_with_org }}
          git add .
          git commit -m "Auto-generated changes. Import ${{ github.event.inputs.full_repo_name_with_org }} repository"
          git push

      - name: Create Pull Request
        run: |
          gh pr create --title "Import ${{ github.event.inputs.full_repo_name_with_org }}" --body "This is an automated PR." --base main --head import-repo-${{ github.event.inputs.full_repo_name_with_org }}
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}